version: "3.9"

services:

  mqtt:
    image: eclipse-mosquitto

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:////app/runtime/server/data/sis.db
      MQTT_HOST: mqtt
      TZ: Europe/Prague
    depends_on:
      - mqtt
    volumes:
      - ./runtime:/app/runtime
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  node:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    restart: unless-stopped
    environment:
      MQTT_HOST: mqtt
      TZ: Europe/Prague
    depends_on:
      - mqtt
    volumes:
      - ./runtime:/app/runtime
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_PROXY_TARGET: http://server:8000
    depends_on:
      - server
