"""initial_schema

Revision ID: 47c4a84f414e
Revises: 
Create Date: 2026-06-08 19:36:14.284784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47c4a84f414e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_conditions', sa.JSON(), nullable=True),
    sa.Column('correction_factors', sa.JSON(), nullable=True),
    sa.Column('weather_api', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hardware_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config_sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('hardware', sa.JSON(), nullable=True),
    sa.Column('irrigation_limits', sa.JSON(), nullable=True),
    sa.Column('automation', sa.JSON(), nullable=True),
    sa.Column('batch_strategy', sa.JSON(), nullable=True),
    sa.Column('logging', sa.JSON(), nullable=True),
    sa.Column('header_pins', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_config_sync_status'), 'node', ['config_sync_status'], unique=False)
    op.create_index(op.f('ix_node_hardware_uid'), 'node', ['hardware_uid'], unique=True)
    op.create_index(op.f('ix_node_name'), 'node', ['name'], unique=False)
    op.create_table('zonelifecycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zonelifecycle_created_at'), 'zonelifecycle', ['created_at'], unique=False)
    op.create_index(op.f('ix_zonelifecycle_deleted_at'), 'zonelifecycle', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_zonelifecycle_node_id'), 'zonelifecycle', ['node_id'], unique=False)
    op.create_index(op.f('ix_zonelifecycle_zone_id'), 'zonelifecycle', ['zone_id'], unique=False)
    op.create_table('irrigationhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('zone_deleted', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed_duration', sa.Integer(), nullable=True),
    sa.Column('target_duration', sa.Integer(), nullable=True),
    sa.Column('actual_water_amount', sa.Float(), nullable=True),
    sa.Column('target_water_amount', sa.Float(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigationhistory_circuit_id'), 'irrigationhistory', ['circuit_id'], unique=False)
    op.create_index(op.f('ix_irrigationhistory_node_id'), 'irrigationhistory', ['node_id'], unique=False)
    op.create_index(op.f('ix_irrigationhistory_outcome'), 'irrigationhistory', ['outcome'], unique=False)
    op.create_index(op.f('ix_irrigationhistory_start_time'), 'irrigationhistory', ['start_time'], unique=False)
    op.create_index(op.f('ix_irrigationhistory_zone_deleted'), 'irrigationhistory', ['zone_deleted'], unique=False)
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relay_pin', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('irrigation_mode', sa.Enum('EVEN_AREA', 'PER_PLANT', name='irrigationmode'), nullable=False),
    sa.Column('local_correction_factors', sa.JSON(), nullable=True),
    sa.Column('frequency_settings', sa.JSON(), nullable=True),
    sa.Column('fallback_strategy', sa.JSON(), nullable=True),
    sa.Column('irrigation_configuration', sa.JSON(), nullable=True),
    sa.Column('emitters_configuration', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_name'), 'zone', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_name'), table_name='zone')
    op.drop_table('zone')
    op.drop_index(op.f('ix_irrigationhistory_zone_deleted'), table_name='irrigationhistory')
    op.drop_index(op.f('ix_irrigationhistory_start_time'), table_name='irrigationhistory')
    op.drop_index(op.f('ix_irrigationhistory_outcome'), table_name='irrigationhistory')
    op.drop_index(op.f('ix_irrigationhistory_node_id'), table_name='irrigationhistory')
    op.drop_index(op.f('ix_irrigationhistory_circuit_id'), table_name='irrigationhistory')
    op.drop_table('irrigationhistory')
    op.drop_index(op.f('ix_zonelifecycle_zone_id'), table_name='zonelifecycle')
    op.drop_index(op.f('ix_zonelifecycle_node_id'), table_name='zonelifecycle')
    op.drop_index(op.f('ix_zonelifecycle_deleted_at'), table_name='zonelifecycle')
    op.drop_index(op.f('ix_zonelifecycle_created_at'), table_name='zonelifecycle')
    op.drop_table('zonelifecycle')
    op.drop_index(op.f('ix_node_name'), table_name='node')
    op.drop_index(op.f('ix_node_hardware_uid'), table_name='node')
    op.drop_index(op.f('ix_node_config_sync_status'), table_name='node')
    op.drop_table('node')
    op.drop_table('globalconfig')
    # ### end Alembic commands ###
